version: '2'

services:
  app:
    image: mofesola/python-app
    build: .
    ports:
      - "5000:5000/tcp"
    env_file:
      - .env

  nginx:
    image: mofesola/webserver
    build: nginx
    ports:
      - "80:80/tcp"

