apiVersion: v1
kind: Service
metadata:
  namespace: python-api
  annotations:
  creationTimestamp: null
  labels:
    io.k8s.service: app
  name: app
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.k8s.service: app
status:
  loadBalancer: {}
