apiVersion: v1
kind: Service
metadata:
  namespace: python-api
  labels:
    io.k8s.service: nginx
  name: nginx
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.k8s.service: nginx
    type: loadBalancer
status:
  loadBalancer:
    ingress:
