apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: python-api
  labels:
    io.k8s.service: nginx
  name: nginx
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        io.k8s.service: nginx
    spec:
      containers:
      - image: mofesola/webserver:${VERSION}
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
